apiVersion: v1
kind: Deployment
metadata:
  labels:
    version: b
    app: spring-boot-istio-routing-service
  name: spring-boot-istio-routing-service-b
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: spring-boot-istio-routing-service
        version: b
    spec:
      containers:
      - livenessProbe:
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreashold: 1
          timeoutSeconds: 1
          exec:
            command:
              - curl
              - http://localhost:8080/health
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreashold: 1
          timeoutSeconds: 1
          exec:
            command:
              - curl
              - http://localhost:8080/health
