apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: client-redir
spec:
  destination:
    name: spring-boot-istio-routing-client
  match:
    request:
      headers:
        uri:
          prefix: /example # prefix
  rewrite:
    uri: /  # drop the /suggest prefix when talking to suggestion-service service such as /suggest/serial -> /serial